name: ${project.name}
description: ${project.description}
version: ${project.version}
author: James Richardson (grandwazir)
website: https://github.com/grandwazir/${project.name} 
main: name.richardson.james.hearthstone.Hearthstone
    
